// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUxe91QiR6bON9SAoO0VbNN-NUHF0meA4',
    appId: '1:728787975612:web:075b5e47545298c7babfb9',
    messagingSenderId: '728787975612',
    projectId: 'bazapp-6c828',
    authDomain: 'bazapp-6c828.firebaseapp.com',
    databaseURL: 'https://bazapp-6c828-default-rtdb.firebaseio.com',
    storageBucket: 'bazapp-6c828.appspot.com',
    measurementId: 'G-FLJZ6W1TKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARUfWBr9bXByhFfMLcgRHR1pjtQpbGUGg',
    appId: '1:728787975612:android:f4aef7caf2ebd9a0babfb9',
    messagingSenderId: '728787975612',
    projectId: 'bazapp-6c828',
    databaseURL: 'https://bazapp-6c828-default-rtdb.firebaseio.com',
    storageBucket: 'bazapp-6c828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSTuJFKddRQ2SEu3Dx4BAEm8xld-1zew',
    appId: '1:728787975612:ios:1b5ac5cfb8700fbfbabfb9',
    messagingSenderId: '728787975612',
    projectId: 'bazapp-6c828',
    databaseURL: 'https://bazapp-6c828-default-rtdb.firebaseio.com',
    storageBucket: 'bazapp-6c828.appspot.com',
    iosBundleId: 'com.example.bazapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSTuJFKddRQ2SEu3Dx4BAEm8xld-1zew',
    appId: '1:728787975612:ios:2a4f93a012f99139babfb9',
    messagingSenderId: '728787975612',
    projectId: 'bazapp-6c828',
    databaseURL: 'https://bazapp-6c828-default-rtdb.firebaseio.com',
    storageBucket: 'bazapp-6c828.appspot.com',
    iosBundleId: 'com.example.bazapp.RunnerTests',
  );
}
